### ISSUE TITLE
Refactor traced_function to work both as a decorator and as a context manager?

### ISSUE THREAD

**Issue by wyattanderson** [uber-common/opentracing-python-instrumentation#108]
We have internally a context manager that lets us quickly throw a trace span around a block of code, e.g.

```
with trace_span(name='some_hot_path'):
    do_expensive_things()
```

I'd love to dump our internal implementation in favor of `traced_function`, ideally without having to move the body of the context manager into a function solely for the purpose of being able to decorate said function with `traced_function`.

I'm imagining something like `mock.patch` etc. that are flexible enough to use either as a decorator or as a context manager:

```
@mock.patch(...)
def test_thing():
    ...

# or

with mock.patch(...):
    do_thing()
```

https://github.com/python/cpython/blob/f84f65be5602e561fef04b66bb487fbc4e560db5/Lib/unittest/mock.py#L1231

I think the basic idea is refactoring `traced_function` into a class that has `__call__`/`__enter__`/`__exit__`. I'm happy to put up a PR, but I wanted to gauge maintainer interest before starting the work.

**Comment by yurishkuro** [comment]
Span object is already a context manager. Are you just adding syntactic sugar to `tracer.start_span`?

**Comment by wyattanderson** [comment]
> Span object is already a context manager. Are you just adding syntactic sugar to `tracer.start_span`?

Yeah, I think so. Mostly just sugar for combining the start of the span as well as the setting of the in-context span, like `traced_function` appears to do.

One of the more specialized cases we have is this, that also sets some tags:

```
@contextlib.contextmanager
def trace_span(operation_name, child_of=None):
    """Creates an opentracing span as a child of the current context span,
    sets tags appropriate for a kafka producer, and starts/finishes the span
    and updates context as appropriate.

    For definitions of terms (span, child, tags, context, etc.) see the
    OpenTracing Semantic Specification at https://git.io/fj3F4"""

    if child_of is None:
        child_of = opentracing_instrumentation.get_current_span()

    span = opentracing.tracer.start_span(
        '{}.{}'.format(__name__, operation_name),
        child_of=child_of,
        tags={
            tags.SPAN_KIND: 'producer',
            # tag key from https://git.io/fj3FW
            'message_bus.destination': FLAGS.job_events_topic,
        },
    )

    with span, opentracing_instrumentation.span_in_context(span):
        yield span
```

It's entirely possible that what I'm asking for is unnecessary/trivial to accomplish otherwise, though.

**Comment by yurishkuro** [comment]
I don't think this wrapper should be combined with `traced_function`, since it's not for "functions".

It looks a bit too specific to your needs, you can just keep it as your own util library (unless you're instrumenting open source modules).

**Comment by wyattanderson** [comment]
Makes sense; I can keep using our library internally. I'd probably propose changing the name if I were to proceed with this, because I was thinking of it in the context of "you can use this to trace a function _or_ a block of code as a context manager". Like, having one tool to reach for instead of two (because we _do_ have places where we use `traced_function` and they feel similar). I'll keep it internal for now, though. Thanks!
