### ISSUE TITLE
Redis hook interface should exactly match StrictRedis

### ISSUE THREAD

**Issue by abeinstein** [uber-common/opentracing-python-instrumentation#23]
The StrictRedis client's [interface](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1130) for `set` is:
`set(self, name, value, ex=None, px=None, nx=False, xx=False)`

We should match that in the client hook to support the case when clients don't specify the keyword argument. There was a nasty bug in production since we was invoking the Redis client like so:
`set('foo', 'bar', 10)` instead of `set('foo', 'bar', ex=10)`. While it may be good practice to always specify the kwarg, we should still support the ability to only use positional args.

**Comment by yurishkuro** [comment]
I think this has been fixed by #19 and released as 2.0.2

**Comment by yurishkuro** [comment]
ah, I see what you mean, the `10` argument would cause issues.
