### ISSUE TITLE
Consider supporting postgres for tracing

### ISSUE THREAD

**Issue by SEJeff** [uber-common/opentracing-python-instrumentation#29]
In addition to mysql.

**Comment by yurishkuro** [comment]
if there postgres drivers that support dbapi2, then it should be simple, as [here](https://github.com/uber-common/opentracing-python-instrumentation/blob/master/opentracing_instrumentation/client_hooks/mysqldb.py).

Are you interested in submitting a pull request?

**Comment by SEJeff** [comment]
psycopg2 does indeed follow PEP249 / dbapi2. I might take a stab at this, thanks!

**Comment by yurishkuro** [comment]
Please reopen if needed
