### ISSUE TITLE
requests?

### ISSUE THREAD

**Issue by ror6ax** [uber-common/opentracing-python-instrumentation#40]
Hi guys, thanks for this awesome instrumentation!

I was wondering if I understood correctly, requests library has pre-made ways of inserting the tracing context into the calls? I see some urllib examples, but no requests...

Also, as a sepatane minor question - how do I get the current span inside of @traced_function? I'm using jaeger_client.

Thanks!

**Comment by yurishkuro** [comment]
Hi @ror6ax ,

Yes, when you call [install_all_patches()](https://github.com/uber-common/opentracing-python-instrumentation/blob/master/opentracing_instrumentation/client_hooks/__init__.py#L30) the `requests` library is automatically instrumented.

All propagation of the current span is done via [request_context.py](https://github.com/uber-common/opentracing-python-instrumentation/blob/master/opentracing_instrumentation/request_context.py) module.

**Comment by ror6ax** [comment]
Wow, nice. Automagically ;)
