### ISSUE TITLE
Is there a possibility to have a example for SQLALCHEMY in FLASK for Database and request traces

### ISSUE THREAD

**Issue by kgrvamsi** [uber-common/opentracing-python-instrumentation#53]
Hi,

I'm confused a bit on how to use the client hooks for a database calls using SQLALCHEMY in Flask app and also the requests either with @traced_function or with before_request and after_request functions.

**Comment by yurishkuro** [comment]
There is an example for Flask that uses this lib: https://github.com/opentracing-contrib/python-flask/tree/master/example

It does not have SQLAlchemy, but it shows how `requests` is auto-instrumented: https://github.com/opentracing-contrib/python-flask/blob/master/example/client.py#L21-L23

The SQLAlchemy instrumentation works in a similar way.
