### ISSUE TITLE
Upgrade Travis CI to support testing with varying dependency versions

### ISSUE THREAD

**Issue by yurishkuro** [uber-common/opentracing-python-instrumentation#87]
A number of PRs going in that require testing with different versions of major dependency versions, like Tornado 4 - 5, Celery 3 - 4 (#85).

Using `tox` was suggested somewhere as an alternative to Travis matrix.

**Comment by asherf** [comment]
https://github.com/uber-common/opentracing-python-instrumentation/pull/96
