### ISSUE TITLE
boto3 and sqlalchemy tracing questions

### ISSUE THREAD

**Issue by r0fls** [uber-common/opentracing-python-instrumentation#88]
I'm trying to trace boto3 and sql alchemy calls within a flask app, and I have a few observations:

1. They seem to require manually instrumenting the span. For example, this generates a boto trace:

```python
        with opentracing.tracer.start_span('boto-call') as span:
            response = ec2client.describe_instances()
            reservations = response.get("Reservations", []) 
```

But simply doing this does not:

```python
            response = ec2client.describe_instances()
            reservations = response.get("Reservations", []) 
```

I face the same issue with the sqlalchemy route. Is this expected? I'm initiating the Jaeger client as follows:

```python
# We need to delay this until after uwsgi forks
@postfork
def configure_jaeger():
    global JAEGER_HOST
    JAEGER_HOST = environ.get('JAEGER_HOST', '')
    config = jaeger_client.Config(config={'sampler': {'type': 'const', 'param': 1},
                                'logging': True,
                                'local_agent':
                                {'reporting_host': JAEGER_HOST}},
                        service_name="jaeger_opentracing_example")
    jaeger_config = config.initialize_tracer()
    tracing = FlaskTracing(jaeger_config, True, app, traced_attributes=['remote_addr', 'headers'])
    opentracing.tracer = tracing.tracer
    install_all_patches()
```

2. The boto3 request doesn't include very much detail. For instance below, I would expect this to capture the type of AWS request being made at the least (in this case `DescribeInstance`):

![Screenshot from 2019-06-13 22-39-22](https://user-images.githubusercontent.com/1858004/59486012-c1a48280-8e2c-11e9-85e7-a06bee741c10.png)

**Comment by Jamim** [comment]
Hello @r0fls ,

There is no release on [PyPI](https://pypi.org/project/opentracing_instrumentation/#history) that has support for `boto3`, it's only available in `master` yet.
Assuming you are trying to use package from `PyPI`, you could try to install `opentracing_instrumentation` form `master`
```bash
pip install git+https://github.com/uber-common/opentracing-python-instrumentation.git
```
and check whether it works for you.
If so, you can ask @yurishkuro to release a new version that will include support for `boto3`.

In terms of `SQLAlchemy`, I unfortunately don't know what's wrong.
Probably, you have to create a separate issue for it and provide some more details.

Best regards!

**Comment by Jamim** [comment]
I've submitted a related issue: #89

**Comment by r0fls** [comment]
Got it, thanks for the clarification @Jamim. I will open a separate ticket with the sql alchemy question and more details.
