### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Jamim** [uber-common/opentracing-python-instrumentation#89]
Hello @yurishkuro,

Could you please release a new version of this library or create some [milestone](https://github.com/uber-common/opentracing-python-instrumentation/milestones) in order to increase the transparency of when it can be released?

Thank you!

**Comment by yurishkuro** [comment]
@Jamim could you help reviewing #84  and #86? We could include them in the released.

**Comment by Jamim** [comment]
Sure, I'll review these PRs.

**Comment by Jamim** [comment]
Hi @yurishkuro,

I've reviewed both PRs, so I suppose that
 - #86 is ready to be merged
 - #84 requires some additional effort

**Comment by yurishkuro** [comment]
@Jamim Something broke in the release process #92, do you have time to have a look?

sdist actually complains that we should be using twine, but I never tried it.
```
WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)
```

**Comment by yurishkuro** [comment]
@Jamim please check 3.1.1 released via Travis deploy.

https://pypi.org/project/opentracing-instrumentation/
